[2023-04-15T20:52:22.200+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-14T15:15:00+00:00 [queued]>
[2023-04-15T20:52:22.244+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-14T15:15:00+00:00 [queued]>
[2023-04-15T20:52:22.245+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T20:52:22.247+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 2
[2023-04-15T20:52:22.248+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-15T20:52:22.308+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonVirtualenvOperator): joke_collector_task> on 2023-04-14 15:15:00+00:00
[2023-04-15T20:52:22.322+0000] {standard_task_runner.py:55} INFO - Started process 346 to run task
[2023-04-15T20:52:22.330+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'joke_collector', 'joke_collector_task', 'scheduled__2023-04-14T15:15:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_joke_collector.py', '--cfg-path', '/tmp/tmpk9bz96cw']
[2023-04-15T20:52:22.332+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask joke_collector_task
[2023-04-15T20:52:22.519+0000] {task_command.py:389} INFO - Running <TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-14T15:15:00+00:00 [running]> on host 09657e5e4ab9
[2023-04-15T20:52:22.762+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=joke_collector
AIRFLOW_CTX_TASK_ID=joke_collector_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-14T15:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-14T15:15:00+00:00
[2023-04-15T20:52:22.772+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv8lk6jyq4 --system-site-packages
[2023-04-15T20:52:22.792+0000] {process_utils.py:183} INFO - Output:
[2023-04-15T20:52:26.744+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 1926ms
[2023-04-15T20:52:26.745+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venv8lk6jyq4, clear=False, no_vcs_ignore=False, global=True)
[2023-04-15T20:52:26.747+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-04-15T20:52:26.748+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
[2023-04-15T20:52:26.750+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-04-15T20:52:26.873+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv8lk6jyq4/bin/pip install -r /tmp/venv8lk6jyq4/requirements.txt
[2023-04-15T20:52:26.899+0000] {process_utils.py:183} INFO - Output:
[2023-04-15T20:52:34.141+0000] {process_utils.py:187} INFO - Collecting requests==2.25.1
[2023-04-15T20:52:34.431+0000] {process_utils.py:187} INFO -   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
[2023-04-15T20:52:34.543+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 547.7 kB/s eta 0:00:00
[2023-04-15T20:52:34.858+0000] {process_utils.py:187} INFO - Collecting idna<3,>=2.5
[2023-04-15T20:52:34.922+0000] {process_utils.py:187} INFO -   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
[2023-04-15T20:52:35.006+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 1.1 MB/s eta 0:00:00
[2023-04-15T20:52:35.019+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8lk6jyq4/requirements.txt (line 1)) (1.26.15)
[2023-04-15T20:52:35.025+0000] {process_utils.py:187} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8lk6jyq4/requirements.txt (line 1)) (4.0.0)
[2023-04-15T20:52:35.031+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv8lk6jyq4/requirements.txt (line 1)) (2022.12.7)
[2023-04-15T20:52:53.287+0000] {process_utils.py:187} INFO - Installing collected packages: idna, requests
[2023-04-15T20:52:53.288+0000] {process_utils.py:187} INFO -   Attempting uninstall: idna
[2023-04-15T20:52:53.293+0000] {process_utils.py:187} INFO -     Found existing installation: idna 3.4
[2023-04-15T20:52:53.296+0000] {process_utils.py:187} INFO -     Not uninstalling idna at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv8lk6jyq4
[2023-04-15T20:52:53.298+0000] {process_utils.py:187} INFO -     Can't uninstall 'idna'. No files were found to uninstall.
[2023-04-15T20:53:03.922+0000] {process_utils.py:187} INFO -   Attempting uninstall: requests
[2023-04-15T20:53:03.924+0000] {process_utils.py:187} INFO -     Found existing installation: requests 2.28.2
[2023-04-15T20:53:03.925+0000] {process_utils.py:187} INFO -     Not uninstalling requests at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv8lk6jyq4
[2023-04-15T20:53:03.925+0000] {process_utils.py:187} INFO -     Can't uninstall 'requests'. No files were found to uninstall.
[2023-04-15T20:53:04.318+0000] {process_utils.py:187} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-04-15T20:53:04.319+0000] {process_utils.py:187} INFO - hvac 1.1.0 requires requests<3.0.0,>=2.27.1, but you have requests 2.25.1 which is incompatible.
[2023-04-15T20:53:04.320+0000] {process_utils.py:187} INFO - docker 6.0.1 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-15T20:53:04.320+0000] {process_utils.py:187} INFO - apache-***-providers-http 4.2.0 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-15T20:53:04.321+0000] {process_utils.py:187} INFO - Successfully installed idna-2.10 requests-2.25.1
[2023-04-15T20:53:04.600+0000] {process_utils.py:187} INFO - 
[2023-04-15T20:53:04.601+0000] {process_utils.py:187} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.1
[2023-04-15T20:53:04.602+0000] {process_utils.py:187} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2023-04-15T20:53:04.844+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv8lk6jyq4/bin/python /tmp/venv8lk6jyq4/script.py /tmp/venv8lk6jyq4/script.in /tmp/venv8lk6jyq4/script.out /tmp/venv8lk6jyq4/string_args.txt
[2023-04-15T20:53:04.858+0000] {process_utils.py:183} INFO - Output:
[2023-04-15T20:53:09.828+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-15T20:53:09.855+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=joke_collector, task_id=joke_collector_task, execution_date=20230414T151500, start_date=20230415T205222, end_date=20230415T205309
[2023-04-15T20:53:09.967+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-15T20:53:10.001+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
