[2023-04-12T11:50:43.950+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-10T00:15:00+00:00 [queued]>
[2023-04-12T11:50:43.963+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-10T00:15:00+00:00 [queued]>
[2023-04-12T11:50:43.964+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:50:43.965+0000] {taskinstance.py:1289} INFO - Starting attempt 2 of 2
[2023-04-12T11:50:43.965+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-12T11:50:43.981+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonVirtualenvOperator): joke_collector_task> on 2023-04-10 00:15:00+00:00
[2023-04-12T11:50:43.985+0000] {standard_task_runner.py:55} INFO - Started process 90 to run task
[2023-04-12T11:50:43.988+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'joke_collector', 'joke_collector_task', 'scheduled__2023-04-10T00:15:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/dag_joke_collector.py', '--cfg-path', '/tmp/tmp4nc48oe1']
[2023-04-12T11:50:43.989+0000] {standard_task_runner.py:83} INFO - Job 90: Subtask joke_collector_task
[2023-04-12T11:50:44.052+0000] {task_command.py:389} INFO - Running <TaskInstance: joke_collector.joke_collector_task scheduled__2023-04-10T00:15:00+00:00 [running]> on host c771c53dc376
[2023-04-12T11:50:44.131+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=joke_collector
AIRFLOW_CTX_TASK_ID=joke_collector_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T00:15:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-10T00:15:00+00:00
[2023-04-12T11:50:44.133+0000] {process_utils.py:179} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv7uice4ln --system-site-packages
[2023-04-12T11:50:44.141+0000] {process_utils.py:183} INFO - Output:
[2023-04-12T11:50:45.738+0000] {process_utils.py:187} INFO - created virtual environment CPython3.7.16.final.0-64 in 784ms
[2023-04-12T11:50:45.739+0000] {process_utils.py:187} INFO -   creator CPython3Posix(dest=/tmp/venv7uice4ln, clear=False, no_vcs_ignore=False, global=True)
[2023-04-12T11:50:45.739+0000] {process_utils.py:187} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2023-04-12T11:50:45.740+0000] {process_utils.py:187} INFO -     added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
[2023-04-12T11:50:45.740+0000] {process_utils.py:187} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2023-04-12T11:50:45.790+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv7uice4ln/bin/pip install -r /tmp/venv7uice4ln/requirements.txt
[2023-04-12T11:50:45.799+0000] {process_utils.py:183} INFO - Output:
[2023-04-12T11:50:51.844+0000] {process_utils.py:187} INFO - Collecting requests==2.25.1
[2023-04-12T11:50:55.085+0000] {process_utils.py:187} INFO -   Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
[2023-04-12T11:50:56.848+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 30.4 kB/s eta 0:00:00
[2023-04-12T11:50:56.866+0000] {process_utils.py:187} INFO - Requirement already satisfied: chardet<5,>=3.0.2 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv7uice4ln/requirements.txt (line 1)) (4.0.0)
[2023-04-12T11:50:56.959+0000] {process_utils.py:187} INFO - Collecting idna<3,>=2.5
[2023-04-12T11:50:58.561+0000] {process_utils.py:187} INFO -   Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
[2023-04-12T11:50:59.973+0000] {process_utils.py:187} INFO -      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 34.5 kB/s eta 0:00:00
[2023-04-12T11:50:59.979+0000] {process_utils.py:187} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv7uice4ln/requirements.txt (line 1)) (2022.12.7)
[2023-04-12T11:50:59.981+0000] {process_utils.py:187} INFO - Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/***/.local/lib/python3.7/site-packages (from requests==2.25.1->-r /tmp/venv7uice4ln/requirements.txt (line 1)) (1.26.15)
[2023-04-12T11:51:07.880+0000] {process_utils.py:187} INFO - Installing collected packages: idna, requests
[2023-04-12T11:51:07.881+0000] {process_utils.py:187} INFO -   Attempting uninstall: idna
[2023-04-12T11:51:07.883+0000] {process_utils.py:187} INFO -     Found existing installation: idna 3.4
[2023-04-12T11:51:07.884+0000] {process_utils.py:187} INFO -     Not uninstalling idna at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv7uice4ln
[2023-04-12T11:51:07.885+0000] {process_utils.py:187} INFO -     Can't uninstall 'idna'. No files were found to uninstall.
[2023-04-12T11:51:08.013+0000] {process_utils.py:187} INFO -   Attempting uninstall: requests
[2023-04-12T11:51:08.015+0000] {process_utils.py:187} INFO -     Found existing installation: requests 2.28.2
[2023-04-12T11:51:08.016+0000] {process_utils.py:187} INFO -     Not uninstalling requests at /home/***/.local/lib/python3.7/site-packages, outside environment /tmp/venv7uice4ln
[2023-04-12T11:51:08.017+0000] {process_utils.py:187} INFO -     Can't uninstall 'requests'. No files were found to uninstall.
[2023-04-12T11:51:08.066+0000] {process_utils.py:187} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2023-04-12T11:51:08.067+0000] {process_utils.py:187} INFO - hvac 1.1.0 requires requests<3.0.0,>=2.27.1, but you have requests 2.25.1 which is incompatible.
[2023-04-12T11:51:08.068+0000] {process_utils.py:187} INFO - docker 6.0.1 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-12T11:51:08.068+0000] {process_utils.py:187} INFO - apache-***-providers-http 4.2.0 requires requests>=2.26.0, but you have requests 2.25.1 which is incompatible.
[2023-04-12T11:51:08.069+0000] {process_utils.py:187} INFO - Successfully installed idna-2.10 requests-2.25.1
[2023-04-12T11:51:08.846+0000] {process_utils.py:179} INFO - Executing cmd: /tmp/venv7uice4ln/bin/python /tmp/venv7uice4ln/script.py /tmp/venv7uice4ln/script.in /tmp/venv7uice4ln/script.out /tmp/venv7uice4ln/string_args.txt
[2023-04-12T11:51:08.853+0000] {process_utils.py:183} INFO - Output:
[2023-04-12T11:51:11.779+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-04-12T11:51:11.792+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=joke_collector, task_id=joke_collector_task, execution_date=20230410T001500, start_date=20230412T115043, end_date=20230412T115111
[2023-04-12T11:51:11.830+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-04-12T11:51:11.849+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
